### ISSUE TITLE
Docs are not clear about where to alias a component for use in a temple template

### ISSUE THREAD

**Issue by Bastes** [mhanberg/temple#106]
**Describe the bug**
Placing aliases (as per the component section in the documentation) to shorten component atoms in a temple view outputs that atom's string representation in the resulting html.

**To Reproduce**
In a temple view:
```elixir
div, do: "Before"
alias WhateverWeb.Components.MyAwesomeComponent
div, do: "After"
```

```html
<div>Before</div>
WhateverWeb.Components.MyAwesomeComponent
<div>After</div>
```

**Expected behavior**
The alias should not appear in the compiled html, or the documentation should point out a way to avoid this.

**Desktop (please complete the following information):**
 - OS: Ubuntu, with docker using elixir:1.11.2
 - Temple Version: 0.6.0-rc.0
 - Elixir Version: Elixir 1.11.2 (compiled with Erlang/OTP 23)
 - Erlang Version: Erlang/OTP 23 [erts-11.1.5] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

**Comment by Bastes** [comment]
Tested adding the aliases to the view module: it works. I'll send a PR to explain this in the `README.md` and `Component` module.

**Comment by mhanberg** [comment]
I apologize that the docs were not clear on this.

Remember, these are normal views! You wouldn't alias a module in an eex template, so you wouldn't do it in a temple-ate.

What you've described is the intended behavior if you were to alias a module in a template.

**Comment by Bastes** [comment]
Yep :) I applied your reviews too (thanks github :wink:).
