### ISSUE TITLE
String interpolation escapes HTML entities

### ISSUE THREAD

**Issue by rktjmp** [mhanberg/temple#121]
**Describe the bug:**

When using `#{...}` in a string, any `&html_entity;` in the string are escaped and rendered as text.

**Desktop:**

    OS: Linux
    Temple Version {:temple, "~> 0.6.0-rc.0"}
    elixir 1.11.3-otp-23
    erlang 23.2.3

**Reproduction:**

In template:
```
div do: "&nbsp;arst"
div do
  "&nbsp;arst"
end

div do: "&nbsp;arst#{1}"
div do
  "&nbsp;arst#{1}"
end
```

Rendered to view:
```
 arst
 arst
&nbsp;arst1
&nbsp;arst1 
```

**Comment by mhanberg** [comment]
This is is intended behavior. When you interpolate a string it compiles to `<%= "my string #{variable}" %>`, which leads to the literal html entities being shown as text. 

You can either emit the variable on a different line than the string literal, or use the `raw` function from Phoenix HTML i believe with the whole string.

**Comment by rktjmp** [comment]
:+1:
