### ISSUE TITLE
Options to conditionally show an element

### ISSUE THREAD

**Issue by mhanberg** [mhanberg/temple#13]
## Proposal

Add some reserved options to elements to conditionally render them.

```elixir
# if option

div if: true do
  text "Hello, world!"
end

# <div>Hello, world!</div>

div if: false do
  text "Hello, world!"
end

# ""

# unless option

div unless: true do
  text "Hello, world!"
end

# ""

div unless: false do
  text "Hello, world!"
end

# <div>Hello, world!</div>
```

These would be preferred over the traditional method

```elixir
if true do
  div do
    text "Hello, world!"
  end
end
```

**Comment by shritesh** [comment]
I think it introduces unnecessary "magic". The following already works and I'd assume is "The Elixir Way" of doing things.
```elixir
if true, do: div do
  text "Hello World"
end
```

**Comment by mhanberg** [comment]
@shritesh That is a good point, I didn't really think about using a single line `if` like that. 

I wonder how to formatter would format that.

**Comment by shritesh** [comment]
It formats exactly as I have presented. Our codebase at work is full of similar patterns. Here's an example screenshot. 

<img width="561" alt="Screen Shot 2019-08-13 at 10 13 01 AM" src="https://user-images.githubusercontent.com/801803/62953342-fa23f680-bdb2-11e9-9fa9-bce36fd7c5b4.png">

**Comment by mhanberg** [comment]
That looks good! Thanks for sharing that.

**Comment by mhanberg** [comment]
I still think that this might be a decent improvement in the future, but i am going to close this issue for now.
