### ISSUE TITLE
Temple 0.8.0 + Phoenix 1.5 results in 'Duplicated modules' when building Mix release

### ISSUE THREAD

**Issue by DavidOliver** [mhanberg/temple#146]
I believe this is because Temple 0.8.0 specifies `phoenix_view` as a dependency, and Phoenix 1.5 has its own `Phoenix.View`. ([Phoenix 1.6 extracts `Phoenix.View` into its own project](https://github.com/phoenixframework/phoenix/blob/master/CHANGELOG.md).)

```
** (Mix) Duplicated modules:
        'Elixir.Phoenix.View' specified in phoenix and phoenix_view
        'Elixir.Phoenix.Template.UndefinedError' specified in phoenix and phoenix_view
        'Elixir.Phoenix.Template.ExsEngine' specified in phoenix and phoenix_view
        'Elixir.Phoenix.Template.Engine' specified in phoenix and phoenix_view
        'Elixir.Phoenix.Template.EExEngine' specified in phoenix and phoenix_view
        'Elixir.Phoenix.Template' specified in phoenix and phoenix_view
```

I'm using Temple 0.7.0 for now. :)

Edit: I don't know if this is worth fixing if Phoenix 1.6 will have its official release soon.

**Comment by mhanberg** [comment]
Ope, good catch. I thought I had tested this in my personal app, but it seems like I forgot.

But, you're right. I don't think I'll plan on fixing this unless a large amount of people start using Temple and also can't upgrade to phoenix 1.6.
