### ISSUE TITLE
DOCTYPE

### ISSUE THREAD

**Issue by mhanberg** [mhanberg/temple#17]
## Description

The HTML spec requires the DOCTYPE to be set in the beginning of the file. Temple currently does not emit this into the markup

### E sigil

Add the following to your my_app_web.ex: `import Phoenix.HTML, only: [sigil_E: 2]`

Then you can add this line to the top of your layout: `partial ~E"<!<DOCTYPE html>"`

### Phoenix.HTML.raw

You can add the following to the top of your layout: `partial Phoenix.HTML.raw("<!DOCTYPE html>")`

## Solution

This `html` macro should add the doctype as well as the opening tag

**Comment by r11132a** [comment]
Should the html macro be set to not take itself as part of an inner block?  Otherwise you'll get something like:

```
temple do
  html do: html
end
```
`{:safe, "<!DOCTYPE  html><html><!DOCTYPE html></html></html>"}`

**Comment by mhanberg** [comment]
@r11132a i don’t think we need to care about that right now. 

Down the line, it might be nice to output a warning about malformed markup, but not for the scope of this issue.
