### ISSUE TITLE
Dynamic attributes

### ISSUE THREAD

**Issue by formoxyz** [mhanberg/temple#183]
**Is your feature request related to a problem? Please describe.**
I want to pass dynamic attributes to a node say div
So i build the attributes as a keyword list like so
```
attrs = [class: "abc", id: "a1", "data-a1": "ABC", "data-a2": "DEF]
```
And then I create the  div like so
```
temple do
	div attrs do
		"Hello World"
	end
end
```
It gives a runtime error that list cannot be converted into string

**Describe the solution you'd like**
I don't know the solution but if attributes are keyword lists then the above should work in my opinion. Please advise if I am doing something wrong.

**Describe alternatives you've considered**
I can build an exhaustive list of attributes and set those not applicable to false. Those won't be rendered in the final markup. But sometimes building an exhaustive list of attributes might not be possible. 

**Additional context**
Say you want to create some components and pass attributes dynamically to them. The attributes might not be known beforehand.

**Comment by formoxyz** [comment]
I have taken this up in the discussion, where it should have been. Sorry I am closing it here.

**Comment by mhanberg** [comment]
Re-opening as this doesn't currently work and needs a tracking issue.

We need something similar to how in heex you can do `<div class="foo" {@rest}></div>`

**Comment by mhanberg** [comment]
I think the cleanest thing I can think of is

```elixir
div let!: bar, class: "foobar", rest!: some_list do
  "hello world"
end
```

Here, we can observe several things. reserved keywords are suffixed by `!`. The `let!` is used for declaring a slot parameter (unrelated to this issue, but would be a change) and `rest!` is used for passing extra dynamic attributes to the tag.

The example in [`Phoenix.Component.assigns_to_attributes/2`](https://hexdocs.pm/phoenix_live_view/0.18.2/Phoenix.Component.html#assigns_to_attributes/1) could be written in temple as.

```elixir
c &my_link/1, href: "/", id: @id, new_window: true, class: "my-class" do
  "Home"
end

def my_link(assigns) do
  target = if assigns[:new_window], do: "_blank", else: false
  extra = assigns_to_attributes(assigns, [:new_window])

  assigns =
    assigns
    |> assign(:target, target)
    |> assign(:extra, extra)

  temple do
    a href: @href, target: @target, rest!: @extra do
      slot @inner_block
    end
  end
end
```

Not sure what the best reserved keyword would be, could go with `rest!` or `extra!`.

**Comment by mhanberg** [comment]
@formoxyz if you get a chance, would you mind testing out this branch?

If you can't, no worries

**Comment by mhanberg** [comment]
I should clarify, you can now pass dynamic attributes with the syntax you proposed as well as mixing them in with static attributes via the `:rest!` attribute.

You can also mix in arguments to a component with `:rest!` as well.

But that just made me think... probably need that for slot attributes as well.
