### ISSUE TITLE
Heex Interop Bug

### ISSUE THREAD

**Issue by georgevanderson** [mhanberg/temple#201]
**Describe the bug**

When attempting to call Heex Components from a temple template, I get an error `the function "inner_block" cannot handle clauses with the -> operator because it is not a macro. Please make sure you are invoking the proper name and that it is a macro`

triggered by [this block in renderer.ex](https://github.com/mhanberg/temple/blob/main/lib/temple/renderer.ex#L94-L100)

Heex Component
```defmodule SlotComponent do
  use Phoenix.Component

  def render(assigns) do
    ~H"""
    <div>This is a slot component
    <%= render_slot(@inner_block, %{}) %>
    </div>
    """
  end
end
```
Temple Component
```
defmodule TempleComponent do
  import Temple
  use TimshelWeb, :live_component
  import Phoenix.LiveView.TagEngine, only: [component: 3]

 def render(assigns) do
     temple do
        c(&SlotComponent.render/1) do:
          "slot"
         end
     end
end
end
```

In local deps I replaced the inner block call with the TagEngine.inner_block, similar to how surface does it which resolved the issue.
```
 block =
          quote do
            unquote(slot.parameter || quote(do: _)) ->
              unquote(ast)
          end

        inner_block =
          quote do
            Phoenix.LiveView.TagEngine.inner_block(unquote(slot.name), do: unquote(block))
          end
```

Looking at the dependencies here though, phoenix_live_view seems to be purposely not a dependency, so probably need to tweak how the inner_block ast is created.

Let me know if theres anything I can do to help! Thanks so much for your library

**Comment by mhanberg** [comment]
Can you provide a full reproduction project? Your snippets look like they have some syntax errors so it's hard for me to say what the problem is.

**Comment by mhanberg** [comment]
This PR demonstrates the problem. https://github.com/georgevanderson/temple_liveview/pull/1

It seems that at some point, the live view compiler stopped assuming a couple of functions would be imported and instead call them remotely.

I'll have to fix the docs to let you know you need to import those somewhere.

**Comment by georgevanderson** [comment]
Thanks so much! Really appreciate the time.
