### ISSUE TITLE
Update phoenix_html dependency to version 4

### ISSUE THREAD

**Issue by meandmark** [mhanberg/temple#232]
**Describe the bug**
When I add Temple as a dependency to a Phoenix project and run `mix deps.get`, I get the following error message:

Because temple >= 0.11.0 depends on phoenix_html ~> 3.2 and your app depends on phoenix_html ~> 4.0, temple >= 0.11.0 is forbidden.

It appears Temple needs to update its phoenix_html dependency from 3.2 to 4.

**To Reproduce**
1. Create a new Phoenix project.
2. Open the project's `mix.exs` file.
3. Add `{:temple, "~> 0.12"}` to the list of dependencies
4. Run `mix deps.get` from the Terminal.

**Expected behavior**
I expect Temple to be added as a dependency to the project.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 12.7.5
 - Temple Version: 0.12
 - Elixir Version: 1.17
 - Erlang Version: 26.2.5
 - Phoenix Version: 1.7.12

**Comment by mhanberg** [comment]
I have to double check but I think phx html can just be removed.

**Comment by mhanberg** [comment]
fixed, released as 0.12.1
