### ISSUE TITLE
path tag nested

### ISSUE THREAD

**Issue by ibnteo** [mhanberg/temple#236]
```
svg do
  path d: "..."
  path d: "..."
end
```
generated the following code:
```
<svg><path d="..."><path d="..."></path></path></svg>
```
the same problem with circle and other tags

**Comment by mhanberg** [comment]
I can't reproduce


![CleanShot 2024-09-26 at 10 24 35@2x](https://github.com/user-attachments/assets/4128707e-9332-432b-8323-b7dc08fb533e)
