### ISSUE TITLE
Pass current `assigns` to component when no assigns are provided

### ISSUE THREAD

**Issue by halostatue** [mhanberg/temple#237]
**Is your feature request related to a problem? Please describe.**

It feels like there should be a little magic involved when doing `c &component/1` with no assigns provided and automatically adding the current `assigns`.

**Describe the solution you'd like**

 That is, these two statements should be equivalent:

```elixir
c &component/1
c &component/1, rest!: assigns
```

This would *not* happen automatically if there are *any* assigns provided to the component call:

```elixir
c &component/1, foo: "bar", baz: "hoge"
```

**Describe alternatives you've considered**

1. Calling a regular function within the `template/1` macro block. This has a downside that there are numerous function names not permitted because they are template keywords (e.g., `c &footer/1` works, but `footer(assigns)` does not). The error case here is ugly (`** (Protocol.UndefinedError) protocol String.Chars not implemented for %{} of type Map.`)
2. Introduce a *different* component keyword that always does `rest!: assigns` (care should be taken to ensure that explicit values would override anything in `rest!: assigns`).
3. Permit a bare `&component/1` which works for "slot-less" components like this. That is:

   ```elixir
   c &component/1 # passes %{} as it does now, accepts explicit assigns
   &component/1 # passes the current `assigns` values but does not accept explicit assigns
   ```

**Additional context**

This isn't *necessary*, but I think it would make it easier to write certain classes of templates with reusable components based on parent state.

**Comment by mhanberg** [comment]
Not entirely sure how I feel about this, it seems like a departure from how all the other component systems work (afaik), it also seems to promote prop drilling, which I thought is considered a bad practice.

also I think you should be able to do `c &component/1, assigns` rather than having to use the the `:rest!` option. that option is for splicing in a dynamic group of assigns with a static group.

**Comment by halostatue** [comment]
I'll try that. If it works, then I'll close this.

The thinking behind this is that there's really two types of components. One is something that encapsulates polymorphic behaviours (that's what is currently supported) and the other is a sort of partial component as is often seen in Hugo templates (those inclusions are done with explicit assigns passing, but `{{ partial "footer" . }}` is easier to read than what I found works so far. That is something that may not be a component as such but a block of code so that your outer template is easier to read.

**Comment by halostatue** [comment]
And I think that approaching it from a "partial" naming perspective instead of "component" for this might be a better name.

**Comment by mhanberg** [comment]
I see, if you actually want to implement partials rather than use components, i believe you can do something like this (untested, but the idea should give you a head start)

```elixir
defmacro partial partial do
  code = File.read!(Path.join("_partials", partial <> ".exs")) |> Code.string_to_quoted!()

  quote do
    assigns = var!(assigns)
    unquote(code)
  end
end
```

```elixir
def template assigns do
  temple do
    partial "header"

    div do
      # stuff
    end
  end
end
```

**Comment by halostatue** [comment]
Call it a "partial function" rather than a partial; I’m not looking for "external" partials.

I tested `c &footer/1, assigns` and it fails with `** (ArgumentError) argument error (stdlib 6.1.1) :maps.from_list([{:assigns, [line: 126, column: 26], nil}])` and only `rest!: assigns` works.

I think that a variation of the `partial` macro you’ve suggested *might* work, but I’ll need to experiment with it to make it work the way that `c` does and as I’ve suggested it.

**Comment by halostatue** [comment]
I have a partial macro that works for my use case and incorporates what *should* work for the partial-file approach you outlined.

If it's something you think that would be useful, I can make a PR for this — but it probably needs much more work to put it directly into the temple AST. This is a bit of a cheat:

```elixir
  defmacro partial(partial, assigns \\ nil) do
    build_partial(partial, assigns)
  end

  defp build_partial(partial, assigns) when is_list(assigns),
    do: build_partial(partial, Macro.escape(Map.new(assigns)))

  defp build_partial(partial, nil) when is_binary(partial) do
    code = load_partial(partial)

    quote do
      old_assigns = var!(assigns)
      unquote(code)
      assigns = old_assigns
    end
  end

  defp build_partial(partial, assigns) when is_binary(partial) do
    code = load_partial(partial)

    quote do
      old_assigns = var!(assigns)

      assigns =
        case unquote(assigns) do
          map when is_map(map) -> map
          list when is_list(list) -> Map.new(list)
        end

      unquote(code)
      assigns = old_assigns
    end
  end

  defp build_partial({:&, _, [{:/, _, [{fn_name, _, _}, arity]}]} = ref, nil)
       when is_atom(fn_name) and is_integer(arity) do
    {:apply, [], [ref, [{:var!, [], [{:assigns, [], Elixir}]}]]}
  end

  defp build_partial({:&, _, [{:/, _, [{fn_name, _, _}, arity]}]} = ref, assigns)
       when is_atom(fn_name) and is_integer(arity) do
    {:apply, [], [ref, [assigns]]}
  end

  defp build_partial({:&, _, [{:/, _, [{{:., _, [_modref, fn_name]}, _, _}, arity]}]} = ref, nil)
       when is_atom(fn_name) and is_integer(arity) do
    {:apply, [], [ref, [{:var!, [], [{:assigns, [], Elixir}]}]]}
  end

  defp build_partial(
         {:&, _, [{:/, _, [{{:., _, [_modref, fn_name]}, _, _}, arity]}]} = ref,
         assigns
       )
       when is_atom(fn_name) and is_integer(arity) do
    {:apply, [], [ref, [assigns]]}
  end

  defp load_partial(partial) when is_binary(partial) do
    "_partials"
    |> Path.join(partial)
    |> File.read!()
    |> Code.string_to_quoted!()
  end
```

I have *verified* that it works for:

- `partial &function/1, data: 1, for: 2, assigns: 3`
- `partial &function/1, assigns`
- `partial &function/1` # implied `partial &function/1, assigns`.
- `partial &Mod.function/1` for all three cases above.

I have not verified the file-based partial (note that mine would expect `partial "footer.exs"` not `partial "footer"`), but I applied what seems to be a logical adjustment to your proposed macro such that it would *restore* the now-unhygienic `assigns` variable after executing the partial code, making it pseudo-hygienic.

My *gut* feeling is that the `partial &function/1` approach would fit nicely with temple's overall approach, but `partial "partial-name"` fits better with tableau.

**Comment by mhanberg** [comment]
Ahh yes, I think that used to work before i introduced the "rest!" syntax (to achieve component compatibility with heex and surface)

**Comment by mhanberg** [comment]
Since you can achieve the desired behavior just using "rest!: assigns", I don't have interest in adding in builtin functionality for this
