### ISSUE TITLE
key :inner_block not found in: %{   socket: #Phoenix.LiveView.Socket

### ISSUE THREAD

**Issue by phanmn** [mhanberg/temple#252]
**Describe the bug**
```
key :inner_block not found in: %{
  socket: #Phoenix.LiveView.Socket<
    id: "phx-GAo9NCdqbbtAFglh",
```

**Screenshots**
<img width="330" alt="Screenshot 2024-11-22 at 15 33 34" src="https://github.com/user-attachments/assets/674f09ff-8bd1-4e92-9de9-b1ad031df797">
<img width="436" alt="Screenshot 2024-11-22 at 15 34 57" src="https://github.com/user-attachments/assets/13433c25-0b3e-4235-b8bb-70389cf7aeb2">

**Desktop (please complete the following information):**
 - OS: macos 14.5
 - Temple Version: 0.14
 - Elixir Version : 1.16.1-otp-26
 - Erlang Version 
 - phoenix_live_view: 0.20.17
 - phoenix: 1.7.14

**Additional context**
I'm trying to use Temple in my current phoenix web live view.

**Comment by mhanberg** [comment]
A Phoenix layout is not a component, so it doesn't receive a slot. 

Replace the `slot @inner_block` with `@inner_content`

If you look at your existing HEEx layouts, you will observe this.

**Comment by phanmn** [comment]
hi @mhanberg,

Thank you for your response, It's work
