### ISSUE TITLE
Phoenix Live View Compatibility

### ISSUE THREAD

**Issue by mhanberg** [mhanberg/temple#26]
This is the tracking ticket for Phoenix Live View compatibility. I will be periodically updating it as I progress and learn more of what is involved.

## Progress

- [x] renders a live view using temple
- [x] renders void elements
- [x] renders non-void elements
- [x] renders text nodes
- [x] renders element attrs
- [x] renders arbitrary expressions
- [x] renders a for comprehension
- [x] renders an if expression
- [x] renders an if/else expression
- [x] renders an unless expression
- [x] renders an unless/else expression
- [x] renders a case expression
- [ ] renders with expression
- [x] renders functions that take a function callback
- [ ] renders the live view form_for that requires the manual closing tag

**Comment by absolutejam** [comment]
Looking forward to this. I'm currently experimenting with Live View for an internal application and wanted to move to using Temple, but didn't know how the two worked together.

Additionally, is it possible to render just a portion of a template using the `temple` macro? I don't want to fully replace my templates at the moment, but it would be nice to transition some of them to using Temple.

**Comment by mhanberg** [comment]
## Update: 10/7/19

I haven't had a chance to work on this in a couple weeks. It is proving to be extremely non-trivial (I expected this), so if anyone wants to try their own hand at implementing it, I would welcome the contributions and ideas.

**Comment by edjroot** [comment]
Would it be feasible (and a good idea) to just precompile the template and pass it to the LiveView engine, like [this](https://github.com/slime-lang/phoenix_slime/issues/71#issuecomment-491586510)?

**Comment by mhanberg** [comment]
> Would it be feasible (and a good idea) to at least initially just precompile the template and pass it to the LiveView engine, like [this](https://github.com/slime-lang/phoenix_slime/issues/71#issuecomment-491586510)?

I am not sure. That solution is very easy for Slime and Phoenix HAML because those libraries produce EEx as a target, while Temple produces Elixir as the target.

Temple is fundamentally different than a traditional templating language, so I think it would be rather difficult to target EEx.

**Comment by mhanberg** [comment]
## Update 4/14/20

I have started up on this again and have already gotten something working. https://twitter.com/mitchhanberg/status/1249924897935106050?s=20

You can follow along the progress by cloning the [`rewrite`](https://github.com/mhanberg/temple/tree/rewrite) branch

**Comment by mhanberg** [comment]
## Update 6/16/20

I have published an alpha release, `v0.6.0-alpha.0`, that is compatible with LiveView.

I have not built a full fledged LiveView app yet, so this will remain on as alpha until I can test it against some real usage.

**Comment by mhanberg** [comment]
Doing some testing with LiveView.

With the current implementation, assignments in a template are compiled into a `<% ... %>` tag in the EEx template.

If you were converting a LEEx LiveView form one-for-one, it would look like 

```elixir
h2 do: @title

f =
  form_for @changeset,
           "#",
           id: "user-form",
           phx_target: @myself,
           phx_change: "validate",
           phx_submit: "save"

label f, :name
text_input f, :name
error_tag(f, :name)

label f, :age
number_input f, :age
error_tag(f, :age)

submit "Save", phx_disable_with: "Saving..."

"</form>"
```

but, this would not work. Because the `%Form{}` is not being emitted into the markup, due to the current implementation.

To get this to work, you must place a call to `f` outside of the match.
```elixir
h2 do: @title

f =
  form_for @changeset,
           "#",
           id: "user-form",
           phx_target: @myself,
           phx_change: "validate",
           phx_submit: "save"

f

label f, :name
text_input f, :name
error_tag(f, :name)

label f, :age
number_input f, :age
error_tag(f, :age)

submit "Save", phx_disable_with: "Saving..."

"</form>"
```

I had a couple of ideas

- Introduce a new operator that would would compile into a match (`f = form_for(...)`), but emit it with the `<%= ... %>` tag. Something like `f <~ form_for(...)`. The downside to that is that most of the extra operators you can define (including `<~`, are treating as pipes, and the formatter doesn't format them very prettily for being used as a match.
- Add special casing to use `<%= ... %>` with certain matches, (this would be configurable). So calling `f = form_form(...)` would use `<%= ... %>` because the rhs was `:form_for`. This is probably tricky if you want to account for calling an unimported version of the function `ModuleA.ModuleB.form_for`. 

None of this feels great, but I'd like to hear some feedback about this in general from anyone who wants to throw in their two cents.

**Comment by zimt28** [comment]
I haven't updated Temple in a while but like the new implementation a lot, well done!

About `form_for/3` and similar cases, what about a wrapping `render_expr` macro or similar?

```elixir
render_expr do
  f =
    form_for(@changeset, "#",
      id: "user-form",
      phx_target: @myself,
      phx_change: "validate",
      phx_submit: "save"
    )
end
```

**Comment by mhanberg** [comment]
@zimt28 

> like the new implementation a lot

Thanks!

> About form_for/3 and similar cases, what about a wrapping render_expr macro or similar?

Can you elaborate a little more?

**Comment by zimt28** [comment]
Not really a macro, but something like

```elixir
test "render_expr" do
    result =
      temple do
        render_expr do
          f = form_for @changeset, Routes.path(@conn, :create)
        end
      end

    assert result ==
             ~s{<%= f = form_for(@changeset, Routes.path(@conn, :create)) %>}
  end
```

```elixir
defmodule Temple do
  # ...

  def traverse(buffer, {name, meta, args} = macro) do
    # ...

    case name do
      :render_expr ->
        {_, _, [[do: expr]]} = macro

        Buffer.put(buffer, "<%= #{Macro.to_string(expr)} %>")
        Buffer.put(buffer, "\n")
```

**Comment by zimt28** [comment]
What about doing it the other way around: Any expression will be rendered by default. If people really want to assign variables or run some other code, which shouldn‘t be done in most cases anyway, they can use a special `code`, `hidden` or similar block.

**Comment by mhanberg** [comment]
> What about doing it the other way around

That is possible, I have played around with a `match!(pattern, value)` function that could be used.

**Comment by zimt28** [comment]
So `match!/2` would be used instead of regular `=` assignments? I don‘t have many templates where I actually run code in the templates instead of views or so, but when it happens it usually requires more than one line. Because of this I‘d prefer a `inline_only` block (naming is hard). Also, it might be a _little_ more obvious what it does than having a special match function.

**Comment by mhanberg** [comment]
I'm currently adjusting the code to make it easier to add parser steps, so we'll what makes the most sense once that's done.

**Comment by zimt28** [comment]
Will `defcomponent` be added again? Two more things I noticed: Should HTML output be formatted? Tags currently don't get indented. And I think `phx_track_static: nil` should lead to `phx-track-static`, not `phx-track-static=""`.

**Comment by zimt28** [comment]
Will known tags like `h1` be usable without a block again (`h1 "Heading`)?

**Comment by zimt28** [comment]
As templates get converted, line numbers are wrong. Maybe there's a way to display correct numbers? Maybe Temple needs to convert line numbers 1 to 1.

**Comment by mhanberg** [comment]
@zimt28 

> Will defcomponent be added again?

I am currently working on an interface for extracting partials. The API will probably not be exactly the same.

> Should HTML output be formatted? Tags currently don't get indented.

They get new lines inserted, but, no indent is not tracked.

> And I think phx_track_static: nil should lead to phx-track-static, not phx-track-static="".

Why? Does this have any impact? 

We might be able to add the following syntax.

```elixir
div [class: "container", :phx_track_static] do
  "foo"
end

# <div class="container" phx-track-static>foo</div>
```

But, as you can see, the brackets are "ugly" 😄

> Will known tags like h1 be usable without a block again (h1 "Heading)?

I'm not sure. Today, you can achieve this by adding `do: `.

```elixir
h1 do: "Heading"

# with attributes
h1 class: "foo", do: "Heading"

# you can even but the `:do` anywhere in the list
h1 do: "Heading", class: "foo"
```

> As templates get converted, line numbers are wrong. Maybe there's a way to display correct numbers? Maybe Temple needs to convert line numbers 1 to 1.

I'll look into this, can you provide more details?  Are you writing temple directly into a view, live view, a template, or a live template? What line numbers are showing up? What file is showing up?

**Comment by mhanberg** [comment]
Temple now works with LiveView.
