### ISSUE TITLE
Compatibility with liveview?

### ISSUE THREAD

**Issue by mindreframer** [mhanberg/temple#5]
Working example here: 
https://github.com/slime-lang/phoenix_slime/commit/604e46b26eafe070b536f5e767771883143bb23b

Cheers!

**Comment by mhanberg** [comment]
@mindreframer

The way Slime and Calliope work is by targeting EEx as the output. This allows them to pipe that into the normal LiveView toolchain. 

However I have some ideas that might work!

**Comment by mindreframer** [comment]
Excited to see them! This could a really great addition to the ecosystem. 

Good luck!

**Comment by jwbrew** [comment]
+1 to this. have just migrated a project to Temple and loving it. would be great to use it for liveview too. 

@mhanberg do you have a channel for discussion? interested in talking about the process

**Comment by mhanberg** [comment]
@jwbrew I created a channel in the Elixir slack: https://elixir-lang.slack.com/messages/CMH6MA4UD

**Comment by mhanberg** [comment]
Closing in favor of #26
