### ISSUE TITLE
CSS support in the DSL?

### ISSUE THREAD

**Issue by garlandcrow** [mhanberg/temple#56]
Maybe this is something I'm missing from scanning documentation and the source code, but is there anyway to something like the script """ ... """ but for styles? Ideally I would like a way to just embed some CSS in one of those blocks and have the classes run through something like PostCSS to transform the classnames, but as a first step I would just like to define CSS in each file.

**Comment by mhanberg** [comment]
You should be able to use the style tag for css.

**Comment by garlandcrow** [comment]
Thanks for the quick response, yea that'll do it! If I get some downtime I might look into how hard it would be to add something like PostCSS if that's something you are also interested in. I like writing in a component sort of way (Svelte) with my CSS in the same file so I'd like if my classnames were local scoped to the component/template file which means doing some transform step to them.

**Comment by mhanberg** [comment]
I don’t think that’s within the scope of this project, but feel free to work on a separate lib!

**Comment by jamauro** [comment]
@garlandcrow curious, did you pursue this?

**Comment by garlandcrow** [comment]
@jamauro no, this is a cool project and I'd like to use it but currently I use live_vue or inertiajs + svelte to do my front end stuff. Now that collocation of JS is a thing in liveview maybe this is a path to do it?
