### ISSUE TITLE
Don't Minify

### ISSUE THREAD

**Issue by JasonMiller** [mhanberg/temple#59]
**Is your feature request related to a problem? Please describe.**
By default, Temple minifies markup, disregarding whitespace within blocks. For example:
```elixir
temple do
  text("Hello,")
  text("World!")
end
```
outputs
```
Hello,World!
```

**Describe the solution you'd like**
All tags should be joined by an newline. Output in the above example should be:
```
Hello, World!
```
Maybe this could be a configurable option.

**Additional Comments**
[This line](https://github.com/mhanberg/temple/blob/5acd6fc0799aaec584f5210ba81188457bdb694c/lib/temple.ex#L46) in the `temple/1` macro calls [this util](https://github.com/mhanberg/temple/blob/5acd6fc0799aaec584f5210ba81188457bdb694c/lib/temple/utils.ex#L60) with `Enum.join("")`.

**Comment by mhanberg** [comment]
Hi, thanks for the bug report. 

The solution is probably to replace the call to `|> Enum.join("")` with `|> Enum.join("\n")`.

**Comment by JasonMiller** [comment]
I agree -- not sure I can see a usecase for joining on `""`. I've only come across one case where I _really_ didn't want whitespace and that could be hacked around with using `partial`.
