### ISSUE TITLE
Allow a list of elements as first param

### ISSUE THREAD

**Issue by zimt28** [mhanberg/temple#64]
Currently it's not possible to do this:

```elixir
defcomponent :top_bar do
  div @children, class: "some classes"
end
```

It looks like Temple tries to convert @children to a string and in some cases succeeds, but not in a clean way. I have quite a few of these wrapper components and think it would be nice to remove those unnecessary `do` blocks.

**Comment by mhanberg** [comment]
That style is only for passing data to a text node.

You can just as cleanly (IMO) write this as

```elixir
defcomponent :top_bar do
  div class: "some classes", do: @children
end
```

**Comment by zimt28** [comment]
This would be nice but doesn't work, it would have to be 

```elixir
defcomponent :top_bar do
  div [class: "some classes"], do: @children
end
```

which I don't like. This is why I preferred the first arg approach. As I'm writing this I'm actually wondering, _should_ the way you suggested work? In this case it's either a bug or `{do: _block}` needs some special treatment.

**Comment by mhanberg** [comment]
I think you're right, the way I suggested doesn't work.
