### ISSUE TITLE
Can temple be adopted partially?

### ISSUE THREAD

**Issue by krushi123** [mhanberg/temple#8]
Can I migrate from eex files gradually? That is, in the templates directory, both eex and exs files can be used. Is it possible?

**Comment by mhanberg** [comment]
@krushi123 Yes.

Instead of calling `use Temple` in your `my_app_web.ex` file, I would call it in each view that will be using temple.

```elixir
defmodule MyAppWeb.ATempleView do
  use MyAppWeb, :view
  use Temple
end
```

You can then use those templates in `eex` templates just like any other partial

```eex
<%= render "my_temple_partial", an_assign: "some assign I need" %>
```

Thanks for asking this question, I will add something to the README!
