### ISSUE TITLE
Component modules seem not to work

### ISSUE THREAD

**Issue by Bastes** [mhanberg/temple#98]
**Describe the bug**
Hi, we've been puzzled when trying to use components, after being misled by the documentations (not checking the latest, our bad), we've checked the latest (for the 0.6.0-alpha4 version) yet all we get when creating a component and using it in a view is an `undefined function` error.

**To Reproduce**
We have configured a path for components:
```elixir
# in config.exs
config :temple, :components_path, "./lib/our_app_web/components"
```

```elixir
# in src/lib/our_app_web.ex
def view
  ...
  use Temple.Recompiler
end
```

We made a component:
```elixir
# src/lib/our_app_web/components/permission_tag.html.exs
span class: "tag-permission", permission: @permission do
  @children
end
```

And we attempted to use it in our view:
```elixir
# in src/lib/our_app_web/templates/role/index.html.exs
permission_tag permission: permission, do: ""
```

What what we get when compiling is:
```
web_1      | == Compilation error in file lib/our_app_web/views/role_view.ex ==
web_1      | ** (CompileError) lib/our_app_web/templates/role/index.html.exs:32: undefined function permission_tag/1
...
```

**Expected behavior**
The component function should be available to the view.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: `Linux b401d3627520 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 GNU/Linux`
 - Temple Version : `0.6.0-alpha4`
 - Elixir Version : `1.10.4`
 - Erlang Version : `Erlang/OTP 22`

**Additional context**
n/a

**Comment by mhanberg** [comment]
The process for creating components has changed, please see the current documentation in the README for an example. 

The things that should get your example working are

- Configuring your component prefix
- Changing the file extension from .html.exs to .ex
- Defining your component using the new module format. 

The undefined function error is from your code attempting to call a function called "permission_tag", which doesn't exist. 

Temple was not able to find your component module so it didn't expand it at compile time. 

Hope that helps

- Mitch 🍻

**Comment by Bastes** [comment]
Thanks :) we had tried (and failed) to use the new method originally, and we noticed that the 0.6.0-alpha.4 tag was not on master and assumed it and the accompanying `README.md` was more up-to-date, not the other way around. We can close that issue (and we'll wave with the new one as soon as we try again on `master`)

**Comment by mhanberg** [comment]
Oh, I apologize. 

It's been some time since I worked on Temple, let me check what code is at version 0.6.0 rc4. 

I have been using master in my own project in order to dog food it easier and haven't been publishing releases as frequently.

**Comment by mhanberg** [comment]
Try renaming your file without html in the extension. 

`permission_tag.exs`

**Comment by Bastes** [comment]
Yes, we did try that and that did not work either.

We're not having it work with the module either, but that's probably because we're not on master. We'll be trying with the latest master.

**Comment by Bastes** [comment]
(thanks for your help too, we appreciate it ; and this is an awesome lib by the way)

**Comment by Bastes** [comment]
We tried and it works :)

We also found a typo in the README (`@behavior` instead of the Elixir `@behaviour` ; I'll send a PR to fix it :smiley:)
